repos:
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args:
          - --safe
          - --quiet

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.5.2
    hooks:
      - id: isort

  - repo: https://github.com/codespell-project/codespell
    rev: v1.17.1
    hooks:
      - id: codespell
        args:
          - --ignore-words-list=ser,nd,hass
          - --skip="./.*"
          - --quiet-level=2

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
        args:
          - --python-version=3.6
          - --ignore-missing-imports
          - --install-types
          - --non-interactive
          - --show-error-codes
          - --disable-error-code=attr-defined
          - --disable-error-code=valid-type
          - --disable-error-code=var-annotated
          - --disable-error-code=dict-item
          - --disable-error-code=misc
          - --disable-error-code=arg-type
          - --disable-error-code=assignment
          - --disable-error-code=return-value
          - --disable-error-code=operator
          - --disable-error-code=type-arg
          - --disable-error-code=has-type
